[package]
name = "v_queue"
version = "0.1.0"
authors = ["itiu <ValeriyBushenev@gmail.com>"]
edition = "2018"
license = "MIT"
description = "simple file based queue"
readme = "README.md"

[lib]
path = "src/queue/lib.rs"

[dependencies]
fs2 = "0.4.3"
scan_fmt = "0.1.3"
crc32fast = "1.2.0"
log = "0.4"
sysinfo = "0.9.0"
